# This is a basic workflow to help you get started with Actions

name: Build JavaServerAction
inputs:
  REPO_TO_BUILD:
    required: true
  BRANCH_TO_BUILD:
    required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: "vantonini/${{ REPO_TO_BUILD }}"
          ref: "${{ BRANCH_TO_BUILD }}"
          token: "${{ secrets.my_pat }}"
      - name: build with maven and java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package          

    
